### ISSUE TITLE
License of logo

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#108]
Rust's logo is licensed as CC-BY 4.0 (c.f. https://github.com/rust-lang/rust-artwork) and R's logo as CC-BY-SA 4.0 (c.f. https://www.r-project.org/logo/). As both licenses allow modification, so there's no license problem with extendr's logo (as long as we distribute the logo as CC-BY-SA 4.0), but probably we need proper attributions to the original copyright holder somewhere. `LICENSE` or `README`?

**Comment by clauswilke** [comment]
Probably `LICENSE`.

On that topic, though: We should consider redrawing the logo. There are obvious drawing artifacts from quickly erasing the Rust R in a bitmap drawing program. Instead, it would be good to take original svg's and do this properly. And maybe also remove the gray oval from the R logo since we have the gear wheel from the Rust logo.

Rust logo svg is here: https://github.com/rust-lang/rust-artwork/blob/master/logo/rust-logo-blk.svg
R logo svg is here: https://www.r-project.org/logo/Rlogo.svg

**Comment by clauswilke** [comment]
Maybe something like this.

![extendr-logo](https://user-images.githubusercontent.com/4210929/103510402-cc69a280-4e2a-11eb-90eb-3d9471dc8ebe.png)

(I did this very quickly. Happy to make changes or receive suggestions, in particular regarding colors.)

**Comment by clauswilke** [comment]
Or this? Picking the color gradient from the R logo.

![extendr-logo-gradient](https://user-images.githubusercontent.com/4210929/103510980-c7f1b980-4e2b-11eb-8926-74a61f2ddd1d.png)

**Comment by clauswilke** [comment]
Actually, thinking some more about this, the artwork probably belongs into a separate repo, and then that's where the license for the artwork would be located.

**Comment by yutannihilation** [comment]
Thanks! I like the gradient. A separate repo sounds nice.

**Comment by andy-thomason** [comment]
Very good. The original was thrown together in Gimp.

**Comment by clauswilke** [comment]
See here:
https://github.com/extendr/artwork/tree/main/logo

@yutannihilation Feel free to add the license info. I didn't have time today to do more than just throw the image files there.

**Comment by yutannihilation** [comment]
Sure, I will.

**Comment by yutannihilation** [comment]
Fixed by https://github.com/extendr/artwork/pull/1
