### ISSUE TITLE
Field accessors

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#184]
This issue is triggered by PR #182.
### Outlining the problem
Extendr does not take into account fields of an exported type and only generates R wrappers for methods. If no dedicated method is declared on Rust side, fields remain inaccessible from R. This can be resolved by creating methods specifically for field access (hereafter, 'accessors'), which is currently done in the test package:
https://github.com/extendr/extendr/blob/ddef053a00ca751921f36f7c98805e85c77000fc/tests/extendrtests/src/rust/src/lib.rs#L88-L97

R wrappers of Rust exports rely on the following design:
1. An environment is associated with the exported class name;
2. Exported functions are assigned to variables in this environment;
3. New instances of this type have `class` attribute set to the type name;
4. Using S3, operator `$` is overloaded for the exported type name: `my_var$my_fun` returns exported function `my_fun`, which can then be invoked with `()`:
https://github.com/extendr/extendr/blob/ddef053a00ca751921f36f7c98805e85c77000fc/extendr-api/src/metadata.rs#L276-L280

For the given above example of Rust code, this approach exposes `my_var$a()` and `my_var$set_a(new_val)`, which works fine.
However, this is not idiomatic R. R operators like `$`, `[`, `[[` have their counterparts, `$<-`, `[<-`, `[[<-`, which support assignment.
So, in R one would expect `my_var$a` returning the value of `a` and `my_var$a <- new_val` setting new value, which is currently impossible.

### Suggested solution
`my_var$my_fun` is a function with a signature `function(self, name)`. Note that from `$` perspective, `my_var$my_fun` and `my_var$my_fun()` are indistinguishable:
``` r
pryr::ast(my_var$my_fun())
#> \- ()
#>   \- ()
#>     \- `$
#>     \- `my_var
#>     \- `my_fun
```
```my_var$my_fun() === (`$`(my_var, "my_fun"))()```

Instead of using just `name` to look for the exported function, the following logic may be implemented:
1. If `name` is exported, obtain this function and return it (without invoking), which is the current behavior;
2. Otherwise, look for `get_{name}`, a signature of getter (read-only field accessor);
a. If found, invoke it and return the result (not the method);
b. Fail with an error otherwise.

This enables the following:
- `my_var$my_fun()` is invoked as before,
- `my_var$get_a()` can be used to obtain `a` if `get_a` method is declared in Rust,
- *new* `my_var$a` now returns the value of field `a` using R-friendly syntax.

This modification is backward compatible. 

The `$` counterpart, `$<-`, is also implemented
`$<-.my_class <- function(self, name, value)` (notice an extra arg value).
This operator supports *only* setters (write-only field accessors).
1. If `set_{name}` is exported, invoke it passing `value` and return `self` (by R convention);
2. Otherwise, fail with an error.

This enables `my_var$a <- 42`, which is ``` `$`(my_var, "a", 42) ```.

This PR is purely syntactic sugar on R side. 

### Discussion
Discord conversations on these topics were, in my opinion, positive. I encourage everyone interested to revisit these discussions, which can be found using keyword 'property'.

**Comment by clauswilke** [comment]
I'm not fundamentally opposed to this idea, but I think taking it slowly is better. Once we've introduced this kind of convention we can't easily take it back, so I wouldn't rush into this. Better to first gain some experience with real-world applications and see where the true sticking points are. For example, it took ggplot years to undo the mistake that `qplot()` was, and it seemed a good idea at the time.

One argument against this is that it's generally considered good design to always create getters and setters for member variables instead of accessing them directly. So why not just stick with this design pattern on the R side rather than creating the illusion that we can access member variables directly, when in fact we can't anyways. (We re-route to the getters and setters.)

You'll also end up with a less confusing API if everything is a function.

@dfalbel Do you want to comment? You're working with a real-world example with classes. Do you see the need to access member variables directly?

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
<blockquote>
One argument against this is that it's generally considered good design to always create getters and setters for member variables instead of accessing them directly. So why not just stick with this design pattern on the R side rather than creating the illusion that we can access member variables directly, when in fact we can't anyways. (We re-route to the getters and setters.)</blockquote>

This is not really about direct access, but rather using existing get/set methods, but with R syntax sugar. I strongly believe that if a class is not some POD (very simple data container), fields should not be accessed directly, but rather through getters/setters, which may have additional logic, e.g. value validation. 

Here is an example that I imagine:
<details>
<summary>Rust</summary>

```rust
struct Point {
    x : f64,
    y : f64
}

impl Point {
    fn new() -> Self {
        Self { x : 0f64, y : 0f64 }
    }
    
    fn get_x(&self) -> f64 { self.x }
    fn get_y(&self) -> f64 { self.y }
    
    fn set_x(&mut self, value : f64) {
        // Validate `value`, i.e. disallow infinity
        self.x = value;
    }
    fn set_y(&mut self, value : f64) {
        // Validate `value`, i.e. disallow infinity
        self.y = value;
    }
    
    // Does not have a backing field
    // yet works as read-only getter
    fn get_norm(&self) -> f64 {
        self.x * self.x + self.y * self.y
    }
}
```
</details>

<details>
<summary>R</summary>

```R
p <- Point$new()
p$x <- 3.0
p$y <- 4.0
p$norm == 5.0
[1] TRUE
```
</details>

**Comment by clauswilke** [comment]
> This is not really about direct access, but rather using existing get/set methods, but with R syntax sugar.

I get that, but it'll look like direct access on the R side. You're adding syntactic sugar that will look like direct access but in reality calls getters/setters. Why not just tell people to use getters/setters directly?

My main argument is more fundamental, though. Syntactic sugar creates technical debt. I've seen it too many times that some syntactic sure was added that seemed like a good idea at the time and later people realize it was actually not so great after all. Two examples I'm very familiar with are `qplot()` and the addition operator in ggplot2. The addition operator in particular was added because the functional interface of ggplot (v1) was perceived to be awkward, but in retrospect it was actually the better design.

Once you add the code you propose to the extendr wrapper generators, you can never take it back. On the flip side, if you don't add it, anybody can add it for themselves in their R packages. So all I'm asking is that we have some patience and see how people use the extendr classes. If there's a strong demand for the syntactic sugar you propose, in real-world examples where code becomes significantly cleaner or easier to read with the sugar, then I'll say by all means go for it.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
I understand your point and I am in no way forcing this solution. I was under the impression that the discussion of this feature had positive feedback, so I made some prototypes, drawing inspiration from base R' active bindings.
If you think it is not the time to add this feature (or it should not be implemented at all), we can close the PR, I have no objections. The important takeaway message is that class support on R side has room for improvement, achieved simply by defining `$` and `$<-` with some extra logic.

However, if extendr will remain as simple as possible, perhaps at some later point in the future we could consider creating an extension crate that will provide syntactic sugar both on R and Rust sides. Perhaps after receiving feedback (and I hope we will get some from users other than core contributors).

**Comment by clauswilke** [comment]
Since the syntactic sugar you proposed was entirely R code, you could consider writing an rextendr function that generates this code. In any case, I'm not that excited about having large amount of R code generated by Rust.

In the long run, I expect that there will be numerous rextendr functions that make development of R packages with extendr code easier. For example, functions that generate the required package structure and functions that extract the wrapper code from the Rust library and place it into the right location. Functions that generate additional, more extended wrapper code would fit right into that vision.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
Ok, I agree. {rextendr} is probably a better place for such code.

**Comment by dfalbel** [comment]
Hi all! Sorry for the very late reply!

I have written a reasonable amount of boilerplate code in hftokenizers to handle getters and setters, eg: https://github.com/mlverse/hftokenizers/blob/e2f26862db795258f274b8d144e593772824599e/R/Encoding.R#L9-L40 and I think it would be helpful to have that functionality.

However, IMHO currently most users will still have to write another R layer around the rust wrappers generated by extendr. 
For example there's no inheritance mechanism, docs auto-generator for classes, public and private methods and etc. 

That said, I think it makes sense to keep things as simple as possible in extendr and we could have another project in the future that allows generating R6 wrappers from the extendr wrappers definitions. This would allow for full feature classes. Solving active fields without using a customized solution, inheritance and all other R6 features.

**Comment by clauswilke** [comment]
@dfalbel The right place for such code may be the rextendr package. I just added code to add extendr scaffolding to an R package and to update the wrapper functions. Adding an additional function that creates more elaborate bindings   would make sense.

**Comment by Ilia-Kosenkov** [comment]
Out of scope for now.
