### ISSUE TITLE
.dylib, not .so files are produced on Mac, which makes installation fail

### ISSUE THREAD

**Issue by TianyiShi2001** [extendr/extendr#19]
When I tried to `R CMD INSTALL .` the `hello` example on Mac, it fails because:

```
cp: ../target/release/libhello.so: No such file or directory
```

and I fount that `libhello.dylib` was produced instead

**Comment by TianyiShi2001** [comment]
A workaround could be changing

```
cp ../target/release/libhello.so .
```

to

```
cp ../target/release/libhello.dylib ./libhello.so
```

in `extendr-api/examples/R/hello/src/Makefile`

although I'm not sure if this is the correct way to do this.

**Comment by lebensterben** [comment]
macOS should produce .dylib.
.so is for Linux.

**Comment by andy-thomason** [comment]
Give @dasmoth a ping on this. He is the master of Mac builds.

**Comment by dasmoth** [comment]
I actually mostly work on Linux too nowadays, but in the past I've done:

    cp ../target/release/libhello.* .

...which seemed to work.

**Comment by andy-thomason** [comment]
谢谢 @TianyiShi2001 

I'll amend this in the package.skeleton generator in the upcoming R package.

If you could let us know if the @dasmoth solution works...

Look out for our Oxford Rust meetup on Thursday.

**Comment by TianyiShi2001** [comment]
By only changing that line to `cp ../target/release/libhello.* .` I got the following error when `R CMD INSTALL .`:

```
Error: package or namespace load failed for ‘hello’ in library.dynam(lib, package, package.lib):
 shared object ‘libhello.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/tianyishi/Library/R/3.6/library/hello’
* restoring previous ‘/Users/tianyishi/Library/R/3.6/library/hello’
```

`libhello.d` and `libhello.dylib` have been copied to the current directory, but only `libhello.so` was searched for.

Changing it to:

```
cp ../target/release/libhello.dylib ./libhello.so
```

made it work in this case. However, it seems that a `.dylib` file isn't always equivalent to a `.so` file (I'm not sure, I have no experience in C/C++) so this is unlikely to be the correct way to do this.

**Comment by lebensterben** [comment]
as I commented before, .dylib is what you should expect to generate on macOS. they're not exactly the same. and simply renaming it won't work

**Comment by lebensterben** [comment]
What you need is something like this:
https://github.com/r-rust/hellorust/blob/master/src/Makevars

Also notice that "Makefile" is not a proper name used by R. By convention it should be "Makevars"

**Comment by andy-thomason** [comment]
For the moment I do not have a mac environment to build this on and so
cannot give you a solution.

The Mac edition of Rust should produce a compatible shared object with the
Mac shared object
both compilers use LLVM under the hood. Chris was recruited by Apple to run
the Xcode team.
Apple objects are "Mach-O" instead of "ELF", but the differences are
minimal.

The Makevars file is used for C/C++ builds. Jeoren had to do a two stage
build -
linking a static library (hence STATLIB) into a shared object which is
unnecessary.
Rust can build shared object libraries directly although the exact runes
for the
Mac build elude us.

Once we get access to a Mac platform or a skilled Mac developer armed with
such,
we can specialise the Makefile accordingly.

**Comment by TianyiShi2001** [comment]
But R seems to work only with `.so`. All R packages I installed have the `.so` file in their `lib` directory:

```
$ pwd && ls */libs
/Library/Frameworks/R.framework/Resources/library

Biobase/libs:
Biobase.so

BiocParallel/libs:
BiocParallel.so

Biostrings/libs:
Biostrings.so

DelayedArray/libs:
DelayedArray.so

...
```

I tried the [r-rust/hellorust](https://github.com/r-rust/hellorust/blob/master/src/Makevars) example noted by @lebensterben , and it outputted `hellorust.so`, not `.dylib`.

**Comment by lebensterben** [comment]
@andy-thomason 
You could be right. But I think we still need a standard "Makevars". Note that R is using a dialect of standard "make".
Specifically, in 1.2.1 of _Writing R Extensions_
> A Makevars file is a makefile and is used as one of several makefiles by R CMD SHLIB (which is called by R CMD INSTALL to compile code in the src directory)

The manpage of `?SHLIB` shows that,
> dllname: the full name of the shared object/DLL to be built, including
the extension (typically ‘.so’ on Unix systems, and ‘.dll’ on
Windows).  If not given, the basename of the object/DLL is
taken from the basename of the first file.

So I **guess**, it will correctly generate `.so` for both macOS and Linux.
Therefore, I suggest to use `Makevars` as other R packages are using.

**Comment by lebensterben** [comment]
Also froo _Writing R Extensions_, in section 5.5
> If the src subdirectory of package contains a file Makefile, this is used by R CMD INSTALL in place of the R CMD SHLIB mechanism. make is called with makefiles R_HOME/etcR_ARCH/Makeconf, src/Makefile and any personal Makevars files (in that order). The first target found in src/Makefile is used.
>
>It is better to make use of a Makevars file rather than a Makefile: the latter should be needed only exceptionally. 

So using `Makefile` actually bypassed the `R CMD SHLIB`.

**Comment by dasmoth** [comment]
I could have sworn that I had seen the `.dylib` version working previously, but it's not now.  However, renaming to `.so` does indeed seem to work fine...

**Comment by lebensterben** [comment]
>I could have sworn that I had seen the `.dylib` version working previously, but it's not now.  However, renaming to `.so` does indeed seem to work fine...

@dasmoth My proposal is to use R's native mechanism to deal with these stuff.
So let "R CMD SHLIB" do its job so we don't need to worry about ".dynlib" at all.

**Comment by andy-thomason** [comment]
I've merged a PR that may make the hello example build on windows and mac. Please can you test it.

**Comment by dasmoth** [comment]
I've tried today's version on a Mac.  `R CMD install .` in the `hello` directory works fine.  However,

```
> library(hello)
> hello()
Error in .Call("wrap__hello") :
  "wrap__hello" not resolved from current namespace (hello)
```

...and...

```
macbook:hello thomas$ nm -g src/hello.so
                 U dyld_stub_binder
```

So it does look as though the Rust function isn't getting built into the .so file.

This could be down to MacOS linker behaviour.  Investigating...

**Comment by dasmoth** [comment]
It's linking `hello.so` with the following command.  Some of the paths will be fairly specific to how my machine is set up, but I would expect the gist of it to remain constant:

         clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/Cellar/r/3.5.1/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o hello.so empty.o -L../target/release -lhello -L/usr/local/Cellar/r/3.5.1/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation

Nothing from libhello.a is making it into the finished .so file.

If I add the (Mac-specific):

      -Wl,-force_load ../target/release/libhello.a

...I get a slew of warnings about hiding symbols, but *do* get a working hello.so which can be loading into R and call `wrap__hello`.  I'm not convinced this is the *right* way to do things, though, but maybe a starting point for someone who has a better rapport with the MacOS linker...

**Comment by andy-thomason** [comment]
It seems that *lld* is being a bit too clever and not linking the static
library
because it is not referenced by empty.c.

The empty c file is needed for the semantics of R CMD SHLIB as this is set
up
for compiling C/C++ code.

Ultimately, we should want to just write lib.rs without any extra
attribution, but the
very manual process that R forces on us is hard to fight.

I would also like to be able to wrap Rust crates with the minimum of
attributes.
For example, we should be able to take a simple crate like *md5* or *crc*
 and
wrap it without modifying the source code. This means using syn to parse
the corresponding source tree, looking for exports.

For strongly templated libraries, we would have to pick particular impls to
wrap

Andy.

**Comment by dasmoth** [comment]
@andy-thomason: In case you haven't already spotted this: I'm actually getting exactly the same behaviour under Linux (_i.e._ .so is generated fine but doesn't contain anything from the cargo-generated .a file).  So not a Mac-specific issue.

Not entirely sure where to go from here.  Ideal might be to have the rust code compiled into .o files instead, so we can all the linking in a single step.  But it doesn't look like cargo supports compiling to .o files, and using rustc without cargo doesn't seem like my idea of fun.

One thing I assume *would* work (and be portable): rather than using "empty.c", generate a minimal C wrapper function for each exposed Rust function.  Ought to be possible to provide some build.rs boilerplate to scan the Rust code and generate matching .c.  But seems like a lot of overhead...

**Comment by andy-thomason** [comment]
This is partly why I was avoiding the C file approach.

We will need a function to be called from the R code to init the .Call
interface anyway,
so a stock .c file might be all we need. Shame, though, it is a bit of a
mess.

R compiles to multiple .o files in an "ar" archive AKA a static library.

This is designed so that the linker can trace the exports through to
functions which are actually
used and eliminate (dead strip) unused functions.

The gnu linker was always terrible at doing this, which is why we had our
own linker
on the Playstation (the SN linker). *lld*, the LLVM equivalent has
inherited much of this
bad behaviour!

You could try, for example, an exported C function with:

```
extern void wrap__hello();

void *my_c_func() {
  return &wrap_hello;
}
```

Which may have the desired effect.

My current default Eoan llvm seems to work ok.

Andy.

**Comment by dasmoth** [comment]
C code along the lines of Andy's suggestion does indeed work (on both Fedora Linux and MacOS).

...and avoids the extra layer of function calls that the version I was thinking of would have added.

**Comment by clauswilke** [comment]
I'm going to close this. I think this is fixed in the extendr repo, but more importantly we now have a minimal working example here: https://github.com/extendr/helloextendr
It compiles on Linux and macOS and passes `R CMD check` on those platforms. Windows remains to be seen.
