### ISSUE TITLE
Integration tests are failing on R devel due to dependency changes in rextendr

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#193]
Some dependencies are not getting resolved when trying to install rextendr under R devel:
https://github.com/extendr/extendr/runs/2119084113?check_suite_focus=true

@Ilia-Kosenkov Could you take a look?

**Comment by clauswilke** [comment]
I suspect the issue is a missing libcurl:
https://github.com/extendr/extendr/runs/2119084113?check_suite_focus=true#step:14:273

**Comment by yutannihilation** [comment]
Seems so. We can just add these lines:

https://github.com/extendr/rextendr/blob/def4813dd003efaa9ea7b7b03cbc625c22dcd651/.github/workflows/R-CMD-check.yaml#L76-L82

**Comment by Ilia-Kosenkov** [comment]
I found this issue in rextendr some time ago when we introduced {devtools} dependency for `rextendr::document()`. I think {devtools} brings in {curl}, which is otherwise not used by {rextendr}, hence the error. 
https://github.com/extendr/rextendr/blob/27347f23189918517c7cc3348a096543235883e1/.github/workflows/test_pkg_gen.yaml#L74-L81
