### ISSUE TITLE
Is this a long-term project?

### ISSUE THREAD

**Issue by waynelapierre** [extendr/extendr#22]
I am quite interested in this project but would like to know if it will be maintained in the long run. For now, it looks like a one-person hobby project.

**Comment by andy-thomason** [comment]
The project has only been around for a while, but we have a small and enthusiastic team of contributors.

We hope to be on-par with RCpp in the near future and then to showcase the simplicity
and flexibility of Rust.

For example, it would be nice to be able to wrap any Rust crate in a way similar to **bindgen** 
with very little user support.

Most importantly, I hope to generate a wide range of parallel and distributed libs for R
which outperform their C/C++ equivalents.

**Comment by waynelapierre** [comment]
That sounds really interesting. I have not used Rust but writing parallel code in C++ is not easy for me even though I have used it for many years. 

The compilation time of C++ functions using Rcpp is relatively long. I heard that Rust compilation time is even longer than C++, would that be a problem?

**Comment by clauswilke** [comment]
Rcpp has architectural issues that make its compile times slow. There's now a new C++ package that resolves many of the issues that Rcpp has: https://cran.r-project.org/web/packages/cpp11/index.html 
I would make it a goal to reproduce the functionality of cpp11 instead of Rcpp. Also note that cpp11 is licensed under MIT, so you can just copy as much code as you want and convert to Rust/reuse the R parts.

Whether compiling Rust projects will be slow will depend on how many different crates the project is using. It should be possible to write small and focused projects that compile fast. Actually, my sinab project, which depends on a fair number of complex crates, compiles in about 5 minutes, and given how much code it pulls in (an entire browser-grade HTML5 parser and an entire browser-grade CSS parser, for example) that's pretty good I think: 
https://travis-ci.org/github/clauswilke/sinab

**Comment by andy-thomason** [comment]
I agree completely with @clauswilke .

**Comment by andy-thomason** [comment]
Rust crates compile to a static library (you can use ar to inspect them).

The more crates you use, the more work the linker has to do and the linker
is likely to be the bottleneck of performance, especially on multicore servers.

With C++, the key to build performance was the "unity build" (see my ACCU article
on the subject with timing examples). The old C model with headers and modules
rapidly becomes N^2 and so most commercial game engines, such as Unreal,
use unity builds of around 30 modules (with 3000+ source files).

The same is true of Rust that build times seem to become N^2 in the numbers of crates
used. No doubt some bright spark will make a Cargo variant that reduces the effective
numbers of crates.

The other performance issue with Rust modules is that it uses an ELF file per function
in the static libraries. Limiting the public exposure of functions would improve
performance, but is rarely done.

On the whole, though, I've managed to keep all my build times below one second
which is the maximum we should tolerate. More than this should be considered a
bug.

**Comment by andy-thomason** [comment]
https://accu.org/journals/overload/25/138/thomason_2360/

**Comment by andy-thomason** [comment]
I'm going to close this as we are proving that thos project is indeed alive and kicking!
