### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#241]
@dasmoth is looking at the `extendr.github.io` website.

I've created a repo to host it and anyone is welcome to contribute.

@dasmoth has been putting together an example in **pkgdown**.

**Comment by dasmoth** [comment]
There's now a working website at https://extendr.github.io/ -- it's generated with `pkgdown` to give a familiar style, and hopefully be reasonably easy to update.  Most of the seed content is based on the existing README _etc._.

The site is hosted with Github pages, and is set to auto-build (in GitHub Actions) on commit to `main`.

**Comment by clauswilke** [comment]
@dasmoth Super, thanks!

Two quick changes I'd suggest:
- I'd delete this sentence: "It is intended to be easier to use than the C interface and Rcpp as Rust gives type safety and freedom from segfaults." No need to speak negatively about other projects or languages.
- Under "Goals of the Project": I think we should say that we support both conversion to native Rust objects and wrappers. Wrappers have turned out to be important (at least in version 0.3 under development). Also, I'd delete "The ultimate goal is to allow the wrapping of existing Rust libraries without markup." I think the markup framework has stabilized and won't change soon.

**Comment by dasmoth** [comment]
Thanks @clauswilke, have modified the front page as suggested.

Obviously, feel free to pull-request (or just commit?  @andy-thomason do you have a preference?) to the extendr.github.io repository if you prefer.

**Comment by clauswilke** [comment]
I think we should typically do PRs and review, just like we do with the code.

**Comment by andy-thomason** [comment]
We can discuss content for the site here.

Are there any "must have"s that we need to address?

**Comment by andy-thomason** [comment]
Thanks, Thomas, for taking the time to do this.
I will hopefully reimburse in Beer tomorrow.

**Comment by yutannihilation** [comment]
I feel the top page should have some R code in addition to Rust code, I made a pull request for this, but I'm not sure if this example code is good enough. If you find any better one, please comment there.

https://github.com/extendr/extendr.github.io/pull/1
