### ISSUE TITLE
TryFrom<Vec<T>> should fail when the vector contains missing values

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#251]
We might have discussed this before, but I feel this should fail.

``` r
rextendr::rust_source(code = r"(
#[extendr(use_try_from = true)]
fn f(x: Vec<i32>) -> i32 {
    x.iter().sum()
}
)", patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/tmp/RtmpcSL9O4/file62d15a1440a6'
#> ✓ Writing '/tmp/RtmpcSL9O4/file62d15a1440a6/target/extendr_wrappers.R'.

f(c(1L, NA))
#> [1] -2147483647
```

<sup>Created on 2021-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I think this behaviour itself is fine, as long as it's obvious the operation is unsafe. Maybe we can provide this as a better name (e.g. [`to_xxx_unchecked`](https://doc.rust-lang.org/std/primitive.f32.html#method.to_int_unchecked)) and use a bit slower but stricter `TryFrom` by default?

**Comment by clauswilke** [comment]
I agree. If the function argument is a vector (so data needs to be copied anyways) we should do element-wise checking.

I'm still not sure how I feel about slices, since they introduce the same problem.

**Comment by Ilia-Kosenkov** [comment]
Perhaps we should embrace what `{cpp11}` does? I.e. provide dedicated types which wrap `SEXP`. And an API to extract 'correct' and 'validated' data on Rust side? 
In the above example, we accept some `Integer`, which verifies only that the vector type is `integer` and the argument is not `NULL`.
Then we can have a method that copies values to `Vec<i32>` (either existing or allocating a new one), panicking if there is an `NA`, or to some `Vec<Option<i32>>`, never panicikng.

For slices, I think I tried this example some time ago. 
We can introduce a wrapper type, say `i32r`, which is exactly 4 bytes in size. This allows us to cast any `&[i32]` to `&[i32r]`.
`i32r` itself is `NA`-aware, and treats `i32.MinValue` as `NA`. 
Implement all the necessary conversions to/from `i32` for `i32r` and voila, validation happens only when the vector element is accessed in contrast to searching the whole vector for `NA`s when crossing `R`-`Rust` boudnary.
This approach should also work for `Vec<i32r>`, allowing direct copying of memory block and deferring validation.

**Comment by clauswilke** [comment]
Yes, I think this is the right way to go. I believe we're already doing this to some extent with the wrapper types, but we don't have a complete API yet.

**Comment by yutannihilation** [comment]
>  We can introduce a wrapper type, say `i32r`, which is exactly 4 bytes in size. This allows us to cast any `&[i32]` to `&[i32r]`.

Considering ALTREP, I feel it's better to proxy to the whole vector, not to the individual element. But we already introduced `Bool`, so this might be fine.

I thought `Int`, `Logical`, `Real` are such things, but it seems a bit different...? They are just iterators, but probably we want to do more than just iteration (e.g. `slice()`).

``` rust
# This works
fn f(x: Int) -> i32 {
    x.sum()
}

# This works
fn f(x: Int) -> i32 {
    x.index(0)
}
```

**Comment by Ilia-Kosenkov** [comment]
Here is an example from the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23%5Brepr(C)%5D%0Astruct%20i32r(i32)%3B%0A%0Aimpl%20i32r%20%7B%0A%20%20%20%20fn%20is_na(%26self)%20-%3E%20bool%20%7B%0A%20%20%20%20%20%20%20%20match%20self%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20i32r%20(std%3A%3Ai32%3A%3AMIN)%20%3D%3E%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20_%20%3D%3E%20false%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0Aimpl%20std%3A%3Aconvert%3A%3AInto%3COption%3Ci32%3E%3E%20for%20%26i32r%20%7B%0A%20%20%20%20fn%20into(self)%20-%3E%20Option%3Ci32%3E%20%7B%0A%20%20%20%20%20%20%20%20match%20self%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20i32r%20(std%3A%3Ai32%3A%3AMIN)%20%3D%3E%20None%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20i32r%20(value)%20%3D%3E%20Some(*value)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0Aimpl%20std%3A%3Aconvert%3A%3ATryInto%3Ci32%3E%20for%20%26i32r%20%7B%0A%20%20%20%20type%20Error%20%3D%20String%3B%0A%20%20%20%20fn%20try_into(self)%20-%3E%20Result%3Ci32%2C%20String%3E%20%7B%0A%20%20%20%20%20%20%20%20match%20self%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20i32r%20(std%3A%3Ai32%3A%3AMIN)%20%3D%3E%20Err(%22Cannot%20convert%20%60NA%60%20value%22.to_string())%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20i32r%20(value)%20%3D%3E%20Ok(*value)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20Verify%20that%20%60i32%60%20and%20%60i32r%60%20are%20binary%20compatible%0A%20%20%20%20assert_eq!(std%3A%3Amem%3A%3Asize_of%3A%3A%3Ci32%3E()%2C%20std%3A%3Amem%3A%3Asize_of%3A%3A%3Ci32r%3E())%3B%0A%20%20%20%20%2F%2F%20Allocated%20vector%20of%20%60i32%60%20values%2C%20similar%20to%20what%20R%20sends%20to%20extendr%0A%20%20%20%20let%20values%20%3A%20Vec%3Ci32%3E%20%3D%20vec!%5B1%2C%202%2C%203%2C%20std%3A%3Ai32%3A%3AMIN%2C%205%5D%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20In-place%20reintepretation%20of%20pointer%2C%20%60view%60%20points%20exactly%20to%20the%20same%20memory%20block%20as%0A%20%20%20%20%2F%2F%20%60values%60%2C%20no%20extra%20allocations%2Fcopying.%0A%20%20%20%20let%20view%20%3A%20%26%5Bi32r%5D%20%3D%20unsafe%20%7B%20std%3A%3Aslice%3A%3Afrom_raw_parts(values.as_ptr()%20as%20*const%20i32r%2C%20values.len())%20%7D%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20Now%20we%20can%20iterate%20over%20the%20slice%20and%20make%20use%20of%20the%20traits%20implemented%20above.%0A%20%20%20%20%2F%2F%20Validation%20happens%20upon%20access%2C%20e.g.%0A%20%20%20%20for%20i%20in%20view.into_iter()%20%7B%0A%20%20%20%20%20%20%20%20let%20j%20%3A%20Option%3Ci32%3E%20%3D%20i.into()%3B%0A%20%20%20%20%20%20%20%20match%20j%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20Some(value)%20%3D%3E%20print!(%22%7B%7D%20%22%2C%20value)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20None%20%3D%3E%20print!(%22NA%20%22)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20println!()%3B%0A%20%20%20%20%0A%7D).

The trick is to declare a type
```rust
struct i32r(i32);
```

And cast a slice of `&[i32]` to `&[i32r]`, which I did using raw pointers.
This involves no copying/allocation, we just get a new 'view' over the same block of memory.

Having `&[i32r]`, we can now implement any number of traits for conversion to/from `i32` with any logic we want, because we own this type.

Speaking of altrep, I am not sure what to do. What is the current behavior of `fn get_vec(x : Vec<i32>) {}` if altrep is passed? 
I feel like if the argument is some iterator `Integer`, then everything is fine and values are produced under the hood. 
Alternatively, we can have some enum wrapper
```rust
enum VecType<'a, T> where T : std::marker::Sized {
    Plain(&'a [T]),
    AltRep(&'a dyn std::iter::Iterator::<Item = &'a T>)
}
```
(I am sure this is horribly wrong, but at least it communicates the idea).
This generic enum can then be used as an argument type like `fn get_vec(x : VecType<i32r>) {}`, and it is up to the user to determine how to deal with the internal representation of the vector.

If altrep is passed to plain `&[i32]`, `&[32r]`, etc, then it should `panic!()`.

We also should ensure that all these types work fine with the `Nullable` enum that is used to allow `NULL` values, e.g.
`Nullable<VecType<i32r>>` allows both plain and altrep vectors of `i32`, as well as `NULL`, and performs no value validation unless the user tries to access individual values.

**Comment by yutannihilation** [comment]
Sorry, I know ALTREP isn't the main topic of this issue, but let me add some comments for clarification.

> If altrep is passed to plain `&[i32]`, `&[32r]`, etc, then it should `panic!()`.

I think it shouldn't. It's often hard for users to know whether it's an ALTREP vector or not, just like integer and double. For example, from users perspective, would it be acceptable if the first one of the following works but the second errors? (Or, what if it's a column of a data.frame created by `readr::read_csv()`, which also uses ALTREP for lazy loading?)

``` rust
some_extendr_func(c(1L, 2L, 3L, 4L, 5L))
some_extendr_func(1:5)
```

So, what should we do? If safety is first, we can just expand the ALTREP. Actually this is what we are doing now by applying `INTEGER()`, or `REAL()`, if I understand correctly.

https://github.com/extendr/extendr/blob/6cf4c1b457d01ce22f2f7fe875a4974e799122eb/extendr-api/src/robj/mod.rs#L696

So, this does require allocation, which is against this assumption.

>  This involves no copying/allocation, we just get a new 'view' over the same block of memory.

Here's the actual behavior:

``` r
rextendr::rust_source(code = r"(
#[extendr(use_try_from = true)]
fn f(x: &[i32]) {
  // Do nothing
}
)", patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/tmp/RtmpkEDXZV/file1a8bb59202477'
#> ✓ Writing '/tmp/RtmpkEDXZV/file1a8bb59202477/target/extendr_wrappers.R'.

x <- 1:5

# ALTREP-form
.Internal(inspect(x))
#> @56348ec17d60 13 INTSXP g0c0 [REF(65535)]  1 : 5 (compact)

f(x)

# expanded
.Internal(inspect(x))
#> @56348ec17d60 13 INTSXP g0c0 [REF(65535)]  1 : 5 (expanded)
```

For reference, cpp11 handles this without expansion. It doesn't provide a scalar representation, but just a wrapper for a vector (c.f. https://cpp11.r-lib.org/articles/cpp11.html#integers).

``` r
cpp11::cpp_function(code = "void f2(cpp11::integers x) {}")

x2 <- 1:5

# ALTREP-form
.Internal(inspect(x2))
#> @56348cca21d8 13 INTSXP g0c0 [REF(65535)]  1 : 5 (compact)

f2(x2)

# not-expanded
.Internal(inspect(x2))
#> @56348cca21d8 13 INTSXP g0c0 [REF(65535)]  1 : 5 (compact)
```

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov 
I want to understand the reason why you prefer `&[i32r]` than implementing some proxy class to the whole vector like cpp11's `integers`. From users perspective, I think it shouldn't matter whether the object is `&[i32r]` or something like `Integer` as long as they provide the same methods and operations. We anyway need to eliminate missing values and convert it to `&[i32]` to pass the values to some other crates that do numeric calculation. Is it the implementational simplicity? Or am I missing some points...?

**Comment by clauswilke** [comment]
I'm starting to think that accepting slices as argument is an inherently flawed approach. The memory model is just too different between R and Rust, and the only way to ensure slices are correct is to copy and check the input data first, which defeats the purpose of a slice.

An abstract wrapper class holding an entire vector of data is much safer, and it can provide iterators etc.

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, it was just an example. My point is -- if we want to accept slices to avoid explicit copying, I suggest to do it through a proxy `i32r` type, which implements data access and validation.
Otherwise, some `Integer` type is the way to go. 
I am fine supporting either `&[i32r]` or `Integer` or both, but I do not like plain `&[i32]`, which requires validation upon function call, or which implicitly treats `NA_integer_` as `std::i32::MIN`, which is incorrect.

With `Integer`, I still think there is a room for `&[i32r]` slice. As Rust is built for performance, we can provide a method that returns something like `Option<&[i32r]>`. If a vector is a regular array, we can get a slice for fast data access, otherwise, we need to obtain an iterator and populate our own data structures.

@clauswilke, I understand it is problematic. However, we now have configuration, so we can choose a safe default approach (i.e. using `Integer` and friends), but also allow other types if configured properly (like right now with `use_try_from`). The challenge is to satisfy both R and Rust users, who are used to -- as you mentioned -- different memory models.

**Comment by yutannihilation** [comment]
Thanks for clarification. Let me think for a while to summarize the possible options. I feel I'm a bit biased to use bare `&[i32]`...
