### ISSUE TITLE
Logicals

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#293]
One last push to finish the wrappers.

The Logicals wrapper uses Bool (rename to Rbool)

Ilia's macros should do this nicely.

**Comment by Ilia-Kosenkov** [comment]
I am unable to painlessly decouple `Bool` (`Rbool`) from `SliceIter`.
I suggest to first retire `SliceIter` #300

**Comment by andy-thomason** [comment]
I can pick this up if you like... You have done all the ground work with the other vectors.

**Comment by Ilia-Kosenkov** [comment]
Honestly, I got stuck because we have `Bool` already that is used in key places (like iterators). Also, because the primitive type is `bool` but R type is `i32`, pretty much all of my macros cannot be used without modifications. I tried making another version of each macros accepting an additional argument for 'actual underlying type', but it becomes a mess. It feels like we will have to write all of the trait implementations for `Rbool` by hand.

Sorry it took me so long and I did not properly communicate my progress to everyone involved.

**Comment by andy-thomason** [comment]
We should rename Bool to Rbool.

I'm working on a PR that uses `Deref` to make Integers and Doubles behave like `&[Rint]` and `&[Rfloat]` This means we can
skip implementing `iter()` and a few other things.

I would rather implement many things by hand anyway, but we can reduce the set that we do.

With `SliceIter` out the way, things should be simpler.

More challenging will be `Complexes` (if that is even a word).

**Comment by Ilia-Kosenkov** [comment]
Perhaps it is better if you @andy-thomason  take over `Logicals`, while I can make an attempt at `Complexes` since it will require adding new features instead of reworking existing types like `Bool`, which I so far have failed.
