### ISSUE TITLE
Hashtable C API

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#343]
Added to libR-sys by https://github.com/extendr/libR-sys/pull/84.

I'm not sure how this is useful, but let me just file an issue here. The corresponding commits on R can be found around here: wch/r-source@c3316e9, wch/r-source@e04f89f

**Comment by multimeric** [comment]
Is this not still relevant?

**Comment by CGMossa** [comment]
I don't think we implemented this. I think we should open a follow up issue about it.

**Comment by yutannihilation** [comment]
Looking at this issue again, I found I've never felt this API is useful. Have you? On Rust, various hashmap implementations are easily available, so I just don't see any motivation to implement this.

**Comment by CGMossa** [comment]
I once did a ML project where I encoded states into an r hashmap... It was
very useful.
It would be cool if we converted certain rust hashmaps to native hashmaps
in R instead of treating hashmaps as name lists.

We currently circumvent this by using externalptr or something like that...
But it could be cool. I'd like an issue and I'd like to be pinged to it.
Tips to implement this will be welcomed in that issue.
