### ISSUE TITLE
RArray.class() returning None

### ISSUE THREAD

**Issue by daniellga** [extendr/extendr#388]
Hi! Is it supposed to be like that? Shouldn't it be returning at least an array class?

```
    let m = RMatrix::new_matrix(2, 2, |r, c| if r == c {1.0} else {0.});
    println!("{:?}", m);
    println!("{:?}", m.class());
```

output:

```
RArray { robj: [1.0, 0.0, 0.0, 1.0], data: 0x562e4f6231e8, dim: [2, 2] }
None
```

**Comment by yutannihilation** [comment]
Yes, this is the supported behavior.

**Comment by daniellga** [comment]
Thank you!

**Comment by yutannihilation** [comment]
I think you are wondering why `m.class()` claims there's no class while R's `class()` says there is. This is because there are some implicit classes that are inferred from the data type or from the data shape. In the case of matrix, the object has no `class` attribute.

``` r
m <- matrix(1:4, nrow = 2)
class(m)
#> [1] "matrix" "array"
dput(m)
#> structure(1:4, dim = c(2L, 2L))

# e.g. data.frame has a class
dput(data.frame())
#> structure(list(), names = character(0), row.names = integer(0), class = "data.frame")
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
