### ISSUE TITLE
Failing io_tests on Ci

### ISSUE THREAD

**Issue by CGMossa** [extendr/extendr#489]
I'm getting this CI error, and I could use help with figuring this out:
```
  error: test failed, to rerun pass `-p extendr-api --test io_tests`
```

There are two tests in here and they run fine on my machine.

https://github.com/extendr/extendr/blob/a2376c08a3efd19b9c8e0d302fb26b1678363889/extendr-api/tests/io_tests.rs#L3

**Comment by multimeric** [comment]
Can you point me to the build itself?

**Comment by CGMossa** [comment]
Yes of course https://github.com/extendr/extendr/actions/runs/4266437196/jobs/7426954401#step:11:1

**Comment by multimeric** [comment]
Hmm tricky. It's only segfaulting on Windows, too. I wonder if this relates to the toolchain changes?

**Comment by yutannihilation** [comment]
Did you try restarting the jobs? I want to know if they fail consistently or occasionally.

I don't know well about RNG, but is it possible that it cannot be tested concurrently because the RNG can be used from various places? If so, it should be put behind `--test-threads=1` just like the tests for graphics.

https://github.com/extendr/extendr/blob/6b0a6c7e75da87600485117a68457b78ee350799/.github/workflows/test.yml#L503-L504

**Comment by Ilia-Kosenkov** [comment]
This test should be considered flaky. I observed it failing from time to time on CI. However, never reproduced locally, so no idea what is wrong with it.

**Comment by CGMossa** [comment]
I guess maybe the rng needs to run in a single threaded manner, but that's
not even the test that is breaking.
And the same issue is happening on another CI run maybe...

**Comment by yutannihilation** [comment]
Sorry, I didn't notice this is not the test that your pull request modified. I restarted the job, so let's see if it works.

https://github.com/extendr/extendr/actions/runs/4266437196/jobs/7437481677

**Comment by yutannihilation** [comment]
Ah, it failed because I bumped the version of libR-sys...

**Comment by multimeric** [comment]
Wait, does that mean there's an issue in libR-sys 0.4?
