### ISSUE TITLE
`impl`s decorated with `#[extendr]` do not support options and have no `TryFrom` impl

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#514]
A discord conversation made me realize:
1. `impl`s generate only `FromRobj` trait impls
https://github.com/extendr/extendr/blob/4cdef47e904986b42b5e8c8499f8faab920d17fa/extendr-macros/src/extendr_impl.rs#L115-L137
2. `impl`s disallow individual annotation on functions, therefore it is impossible to configure member functions (e.g. `use_try_from`)
https://github.com/extendr/extendr/blob/4cdef47e904986b42b5e8c8499f8faab920d17fa/extendr-macros/src/extendr_impl.rs#L93-L100

Code generated for `impl`s should be expanded to match that generated for standalone functions.

**Comment by CGMossa** [comment]
This has been dealt with, because  `TryFrom` is now the default.

However, (2) is still somewhat relevant: We don't support individual `#[extendr]` attributes on impl-block `fn`-items. There aren't many options available at the moment, but _maybe_ just adding `#[extendr(use_rng = true)]` could be a good prototype to try out.
