### ISSUE TITLE
Clippy warnings

### ISSUE THREAD

**Issue by jbabyhacker** [extendr/extendr#54]
There are numerous clippy warnings. Most are related to publicly exposed unsafe functions. I would like to go an fix this, but what is the guidelines in the project regarding public unsafe functions? Allow them or wrap them so no public functions are unsafe?

**Comment by clauswilke** [comment]
Are these extendr-api functions or libR-sys functions? I think libR-sys needs publicly exposed unsafe functions, because that's its entire purpose. extendr-api probably shouldn't expose any unsafe functions.

**Comment by jbabyhacker** [comment]
These are extendr-api functions. Unsafe makes sense for libR-sys.

**Comment by jbabyhacker** [comment]
So I looked into this a little deeper. Because of the separation between extendr-api and extendr-macros, and the use of raw pointers, the only way to not have unsafe code publicly exposed would be to combine the two crates. Not sure if you want to do that.

**Comment by clauswilke** [comment]
Rust procedural macros need to live in their own crate. Hence, there's no way to combine the two crates into one.

**Comment by yutannihilation** [comment]
Sorry to ask a Rust newbie question here... How can I see these "Clippy warnings"? Is it just running `cargo clippy` on console? If so, I don't see any warnings. Do I need some additional linting configurations?

**Comment by yutannihilation** [comment]
> I don't see any warnings

Now I see the warnings.

https://gist.github.com/yutannihilation/485ba77d2584784fd339c7979a786b22

**Comment by yutannihilation** [comment]
I'm wondering whether we should monitor clippy warnings on CI or not.

As clippy's warnings may contain false-positives, I now feel the warnings should not make CI fail (the errors might, though). In terms of this, this GitHub Action seemed very useful in that this adds comments instead of failure.

https://github.com/actions-rs/clippy-check

But, its README says there's one big limitation:

> Due to token permissions, this Action WILL NOT be able to post clippy annotations for Pull Requests from the forked repositories.

Due to this, the action suppresses clippy warnings for pull requests from others, which makes many warnings unnoticed. So, I now feel it's not worth checking clippy warnings, considering the complexity.

Any thoughts?

**Comment by clauswilke** [comment]
I agree, let's not have CI fail due to clippy warnings.

It would be good, though, if the clippy warnings could at least be output somewhere so we can monitor them easily if we want to. We have a lot of warnings that probably should be fixed, and I had never seen them before you posted them.

**Comment by yutannihilation** [comment]
I see. I'll look for other options.
