### ISSUE TITLE
Unable to compile with R 3.2.0

### ISSUE THREAD

**Issue by jbabyhacker** [extendr/extendr#55]
The following includes cause extendr to not be able to be built against R 3.2.0. I would like to do conditional compilation to allow extendr to build.

https://github.com/extendr/extendr/blob/5ebf0ab1dfc6e9574fe80526dca97ecf8377223b/extendr-api/src/lib.rs#L79-L83

**Comment by clauswilke** [comment]
We haven't had a conversation as a group about which R versions to support. I would argue that R 3.2 is too old. Trying to support it will divert scarce development resources from a project that is in its infancy and barely working with R 4.0. Also, many popular packages are starting to drop support for R 3.2. For example, ggplot2 will almost certainly stop supporting it with the next release.

You may be better off just taking the parts of extendr that you need and putting them into a separate crate. Because for sure all the `#[extendr]` and `extendr_modules!` work will not easily transfer to R 3.2, so that would be major parts of the project that need to be disabled.

@andy-thomason Any opinions on this?

**Comment by clauswilke** [comment]
Would also be good to get @yutannihilation's perspective.

**Comment by jbabyhacker** [comment]
That is fine. I will fork the repo and when my R code is compatible with 4.0, I'll come back to the mainline.

**Comment by yutannihilation** [comment]
I agree R 3.2 is too old.

I think we should focus on supporting only for the released and development version of R at this stage. I don't know well about the changes of R's C API between the versions, but it probably requires some additional work to some extent, but it's unclear if these efforts will pay.

> Also, many popular packages are starting to drop support for R 3.2. For example, ggplot2 will almost certainly stop supporting it with the next release.

Honestly, I feel even the tidyverse's ["four previous version"](https://www.tidyverse.org/blog/2019/04/r-version-support/) rule is too tough for ordinary package developers. For example, Rcpp doesn't provide perfect support for that old versions, and this is why r-lib people create cpp11 in my understanding. Long-term support is important in the world of enterprise, but I believe the speed of development is more important here, at least at this stage.

**Comment by andy-thomason** [comment]
Thomas did make a PR where he put #[cfg] guards on the R version so that
the API did not try to use them.

If you absolutely have to run on 3.2, please can you surround the missing
functions with guards instead of commenting them out.

If anything is absolutely essential, like the protection mechanism used by
Owned Robjs, we may have to discuss an alternative.

**Comment by andy-thomason** [comment]
I'll close this if no one objects.

**Comment by clauswilke** [comment]
Yes. libR-sys currently supports R devel, R release, and R oldrel with precomputed bindings. We may extend this to more versions at some point, but I doubt we'll ever go as far back as R 3.2.

**Comment by jbabyhacker** [comment]
Recent changes made to this library now allow it to build and work with R 3.2.
