### ISSUE TITLE
Windows CI failing with mingw-w64-x86_64-pkg-config and mingw-w64-x86_64-pkgconf are in conflict.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#59]
Windows CI failing with mingw-w64-x86_64-pkg-config and mingw-w64-x86_64-pkgconf are in conflict.

Do we need pkg-config anymore?

We should just remove it.

**Comment by clauswilke** [comment]
It's this line here:
https://github.com/extendr/extendr/blob/53e381023a542f5ba075c32566aae395e9a48e2d/.github/workflows/test.yml#L69

@CGMossa Was there a reason why you added this dependency? It's not used anymore by libR-sys, I believe.

**Comment by CGMossa** [comment]
I tried to guess what packages might actually be needed. This is a guess, and can be removed if there is a problem. The reason why it works, is that the default installation of msys2, that is on the virtual machine used for windows builds, has a lot of things in it, and we are only using those things. A fresh msys2 installation does not contain these things that we need. I don't know what we need, because initially I made it work with installing groups of packages.
