### ISSUE TITLE
ToVectorValue not implemented for Rfloat 

### ISSUE THREAD

**Issue by JosiahParry** [extendr/extendr#592]
I've encounterd this issue when trying to create an RArray or RMatrix from `Doubles`. I cannot think of a simpler reprex for this scenario. 

```rust
#[extendr]
fn bad_rarry() -> RArray<Rfloat, [usize; 2]> {
    let v = vec![2.0, 1.0, 0.5];
    Doubles::from_values(v)
        .iter()
        .collect_rarray([1, 3])
        .unwrap()
}
```

**Comment by daniellga** [comment]
I am without a PC to test, but have you tried the code below?

#[extendr]
fn bad_rarry() -> RArray<Doubles, [usize; 2]> {
    let v = vec![2.0, 1.0, 0.5];
    v.iter().collect_rarray([1, 3]).unwrap()
}

To me it doesn't make sense `RArray<Rfloat, [usize;2]>`, since you create a matrix from vectors, so the correct would be `RArray<Doubles, [usize;2]>`.

I suppose it should work also for a `Vec` of `Doubles` instead of a `Vec` of f32.
