### ISSUE TITLE
Invalid external pointers crash the R session

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#709]
See pola-rs/r-polars#874

**Comment by eitsupi** [comment]
Thank you.

I am curious as to why you are a member of this organization but make massive changes to your own fork.

I would think that changes so huge that no one can review them and they are unlikely to be merged here?
(It seems to me that even small changes are hardly merged here in the first place, and I fear that the extendr project is almost at a standstill now)

Should we switch to your fork?

**Comment by CGMossa** [comment]
My intention is not to fork extendr. I've made a fork, with the intention of figuring out the big challenges we have in extendr-development. I'm periodically rebasing / sorting commits to merge them into single-feature-commits, so they can be used as basis for PRs. 

extendr development is very tangled, and I wanted to untangle it bit by bit. Limitation in Rust and R makes it hard to work on a single thing and just make it into a solid, review-ready PR.

Currently, what my fork does:

* Adds `libR-sys` and `rextendr` as git submodules to extendr, so the syncing between versions can happen more holistically. This has been very nice..
* Using `parking_lot` for R_API-lock.
* Fix: issue with returning &Self / &mut Self from extendr-impl
* conversion of strings made more "efficient" because we no longer look for the `NUL` https://github.com/CGMossa/extendr/commit/c62e6537ebd8632f03eb9fd6bfad0168d8f1b9e1
* Added support for `enum` as R `factors` via `#[extendr]`-macro on `enums` https://github.com/CGMossa/extendr/commit/3cbc9a4e652d87e909427cec9fde3706c58d426d
* Use `use_try_from` as default and removed `FromRobj` completely.
* Removed one macro from R-internals stuff https://github.com/CGMossa/extendr/commit/9332208292985f20bdf3daa810055d3b74a18791

Originally, what I wanted to do is simply figure out the multi-threading issues we have been having. And little by little the fork has grown a little too big.

The goal is to merge the good part over.

**Comment by eitsupi** [comment]
Thank you for your detailed explanation. It would be great if they were merged.
