### ISSUE TITLE
Replace manual conversions to TryFrom/Try traits

### ISSUE THREAD

**Issue by latot** [extendr/extendr#732]
Hi, there is some sections that try to convert values like this: https://github.com/extendr/extendr/blob/1b6a5820866174cdebb9b729b2a4cbc94a1a4327/extendr-api/src/deserializer.rs#L867

```rust
        if v <= i32::MAX as u64 {
            Ok(Integers::from_values([v as i32]))
        } else {
            Err(serde::de::Error::custom("out of range for Integers"))
        }
```

Instead we should just use ```u64::try_from(v)```, if is not implemented use a wrapper or something, but skip doing this manually.

**Comment by Ilia-Kosenkov** [comment]
These casts are perfectly safe because `i32::MAX` fits within `i64` range.

**Comment by CGMossa** [comment]
I have seen that the serializer/deserializer breaks in certain cases. I think I mentioned it in the discord. Plus, if you look a little above the code in OP, there is this `if v > i32::MIN as i64 && v <= i32::MAX as i64`, and beneath it,
there is a call to `Integers`, baring the NA values that may be represented in the serialised-blob.

That's.. an issue.

**Comment by latot** [comment]
@Ilia-Kosenkov you are right, they are safe, is just this issue is not only a matters of working code.

In rusty sense, "```i32::MAX``` is safe because is inside the ```i64``` range" yes! and also, due the same reason exists the ```From``` trait, if exists a safe conversion it will exists. While at the same time, if the conversion exists but can fails like from ```i64``` to ```i32```, instead of the ```From``` trait, will exists the ```TryFrom``` one!

The ```TryFrom```/```From``` traits exists to organize this, so even if don't know exactly all details of the type, we can convert them safely, actually anyone can make an error thinking the conversions, maybe there was a special case we didn't thought, and have this traits are great to organize that.

The big advantage of this, is that helps to more ppl be able to help with projects! helps in safer code, maintainability across different ppl :)

Obvs there is some special cases where ```as``` is the right keyword, but for conversions, is good use ```TryFrom``` and ```From``` to organize the code.

**Comment by CGMossa** [comment]
I've been following along with this, and I'm very much pleased that you're attempting a substantial contribution to extendr! More of this please.
Extendr is a very particular project; It is far from a true rust-project, as it is more C/FFI heavy, and opinionated code, than anything else. There are compromises everywhere, and attempts at venturing forth where no-one else has been before. Everything is brittle, and sometimes it is easier to show, rather than tell. There are several serious PRs that have been left unmerged, or downright closed. PRs that targeted a missing functionality, that have interested parties. 

But that is the nature of this project. It isn't a straightforward where the objectives are, although the vision is more or less unified. The objectives vary with deeper understanding of what can be done between Rust and R.

This PR fails to show utility in the areas I'm focused on. I don't see it offering something better than the present. I also think it makes things more verbose than need be. If there is a rust release that permits full `TryFrom`-conversions between all standard types, then we can think about that! But that moves the MSRV further along, and that is a problem with the various platforms, extendr is expected to work on. 

But keep exploring! Keep opening PRs that illustrates certain ideas, and one day, the conversation might lead to progress. For now, I'd say that I'm not in favour of this particular PR.

**Comment by latot** [comment]
!! @CGMossa @Ilia-Kosenkov I notice.... confussion! I was not able to explain properly the issue above!

The function is trying to convert ```v``` to ```i32``` manually, while should be done with ```TryFrom```/`` `From``` trait instead!

**Comment by CGMossa** [comment]
Closing this issue, as I believe we've dealt with this.
