### ISSUE TITLE
Lower the MSRV?

### ISSUE THREAD

**Issue by andyquinterom** [extendr/extendr#799]
I got the following comment from CRAN today in the morning.

> Rust 1.69.0 is only 14 months old -- it is unreasonable to expect OSes
> to have a more recent version (and LTS versions could be a lot older,
> e.g. 1.41.0).

Is it worth an effort from my side to try to lower to MSRV? 

Thinks I would probably need to do:

1. Remove workspace specific DX features that could be replaced with a script.
2. Check for dependencies and their MSRV. I see for example `faer` has a `1.67` MSRV.
3. Extensibly test locally to see if it is possible to lower the MSRV.
4. Add proper CI for testing. 

If this effort is not worth it, perhaps we need to document in the system requirements and the minimum supported R version of `rextendr`.

Currently `rextendr` has the following R requirements.

```
Depends:
    R (>= 4.0)
```

**Comment by JosiahParry** [comment]
I submitted a package to CRAN a few weeks ago with the latest version of extendr (from a commit) and it wasn't an issue. It appears that this change was introduced in https://github.com/extendr/extendr/pull/742. 

Do we know _why_ the MSRV was bumped other than CI was failing?

**Comment by eitsupi** [comment]
The MSRV for extendr has been tested and is declared below.

https://github.com/extendr/extendr/blob/cb85a21a90c3fcb538a40fcea03058454edb3dac/Cargo.toml#L17-L20

I don't think it is worth the maintenance cost for the R package to keep the MSRV at 1.69 for submission to CRAN.
I have heard that this year Cargo will be coming out with edition 2024 which will have MSRV-aware dependency resolution, which will be of great benefit to many users like us, but it may be 10 years before CRAN replaces Fedora 36, so we will not see the benefit for years to come.
I recommend that you give up CRAN in favor of R-universe.

That said, I am aware of several alternatives for submitting to CRAN.

1. The gifski package (not to mention the oldest R package using Rust on CRAN) has a mechanism to replace the Rust source code when it detects old rustc. <https://github.com/r-rust/gifski/blob/a5d830a49f591fbc444be8399e68094f457daa5f/configure#L11-L27>
2. savvy's MSRV is currently below 1.69 (although I believe this is only true for now and does not guarantee CRAN support for the next 10 years). <https://github.com/PRQL/prqlc-r/blob/e22c19b2dfc02e11526c68cb3a7eb9d727bc4e6c/src/rust/Cargo.toml#L2-L5>

**Comment by CGMossa** [comment]
> Do we know _why_ the MSRV was bumped other than CI was failing?

There is absolutely no reason on our end as to why the MSRV was bumped.

It is due to a dependency on `bindgen`, and that dependency is maintained by the Rust people directly.

The thing we could do, is what @yutannihilation have suggested before, and it is: https://github.com/extendr/libR-sys/issues/189

We already have an `xtask` in `extendr`, so a similar one should be setup for `libR-sys`. Then the dependency on `bindgen` should be removed, and that's it.

Unfortunately, I won't do that, but I'd happy to support the preparing of a PR for that. I will have to see it before I know if I think it is a good idea to _merge_ it.

**Comment by yutannihilation** [comment]
@CGMossa 

> absolutely no reason on our end

You chose to depend on that version of bindgen. You could have reverted the change if you care about CRAN, but you chose not to do it despite my warning. That's the reason.

I'm not saying the decision is good or bad (again, I think it's a good idea to stop supporting CRAN), but you should not pretend as if there were no other option. You chose to introduce this breakage.

**Comment by CGMossa** [comment]
Thanks for replying to this. As far as I can remember, we had `bindgen` at version `0.69.4` and it didn't break MSRV. Then, all of a sudden, it started to. This can happen if someone published a semver-compatible package, that is a dependency of `0.69.4`, but it breaks MSRV specified in `bindgen`. I saw that the `bindgen` people just _recently_ changed the MSRV requirement on their repository. 

But now, let me investigate it again, and write here the outputs I get:

```sh
cargo clean; rm Cargo.lock; cargo msrv --min 1.67.0
# redacted
Check for toolchain '1.69.0-aarch64-apple-darwin' failed with:
┌──────────────────────────────────────────────────────────────────────────┐
│ error: package `home v0.5.9` cannot be built because it requires rustc   │
│ 1.70.0 or newer, while the currently active rustc version is 1.69.0      │
│ Either upgrade to rustc 1.70.0 or newer, or use                          │
│ cargo update -p home@0.5.9 --precise ver                                 │
│ where `ver` is the latest version of `home` supporting rustc 1.69.0      │
└──────────────────────────────────────────────────────────────────────────┘
   Finished The MSRV is: 1.70.0
```

Now, I can change the version of `bindgen` to `0.68` in `libR-sys`s `Cargo.toml` and run `cargo clean; rm Cargo.lock; cargo msrv --min 1.67.0`, I still get that MSRV is `1.70.0`. 

And this version was really a long time ago, where `bindgen` didn't break the previous set MSRV. 


I'm very thankful that you guys follow-up on these details, because there are many of them, and I can't keep up. But this one, I was very sure that I checked thoroughly, and I just redid it, and it holds true. We didn't upgrade `bindgen` to a MSRV breaking version. Something else did.

**Comment by eitsupi** [comment]
Since the stable version of Cargo tries to use the most recent patch version, isn't it possible to fix MSRV without a lock file (rust-lang/cargo#13873)?
If you care about MSRV, you should add the lock file to the repositories and test that.

At least for now, using the nightly version of Cargo, it seems possible to create a lock file with MSRV-aware dependency resolution without using edition 2024 (although I haven't tried it).

**Comment by CGMossa** [comment]
I believe someone broke MSRV of the versions, without incrementing semver. This should have been done. I am hoping the rust folks will rectify this issue soon, without having to rely on nightly. 

If anyone is up for experimenting with this, I'd be happy to assist in a PR.

**Comment by eitsupi** [comment]
> I believe someone broke MSRV of the versions, without incrementing semver. This should have been done.

See previous discussions (rust-lang/api-guidelines#231).
At this time it is not possible to set MSRV without using a lock file.

> This should have been done.

As you can see from the discussion I linked to, there is no such consensus within the Rust ecosystem.

**Comment by yutannihilation** [comment]
@CGMossa 
I apologize that I didn't know the version resolution of Rust is this painful. I hope https://github.com/extendr/extendr/pull/803 can be an inspiration to you. One bad news is that it seems xtask is actually requires 1.70 by requiring such a version of clap.

**Comment by CGMossa** [comment]
Thanks! I also tried this https://github.com/extendr/libR-sys/pull/247

**Comment by eitsupi** [comment]
Even worse, the `rust-version` field is optional, and there is no guarantee that this value is correct unless the author has tested it, so I think we need to monitor with a lock file and dependabot to keep MSRV.

When I set the CI for MSRV, I should have added a lock file. But I didn't realize that at the time, sorry.

**Comment by CGMossa** [comment]
@andyquinterom Hello! We have updated extendr and lowered MSRV. Do you have a package that is on CRAN, then please update it. We have sent out various updates to packages on CRAN. Did we miss yours?

Closing this issue, but feel free to reply here.
